//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XMCEntitites : DbContext
    {
        public XMCEntitites()
            : base("name=XMCEntitites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<XMC_Dokument> XMC_Dokument { get; set; }
        public DbSet<XMCPozicion> XMCPozicions { get; set; }
        public DbSet<XMCProjekt> XMCProjekts { get; set; }
        public DbSet<XMCPune> XMCPunes { get; set; }
        public DbSet<XMCStatistika> XMCStatistikas { get; set; }
        public DbSet<XMCTask> XMCTasks { get; set; }
        public DbSet<XMCTipologjia> XMCTipologjias { get; set; }
        public DbSet<XMCUser> XMCUsers { get; set; }
    }
}
