//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XMCEntities : DbContext
    {
        public XMCEntities()
            : base("name=XMCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<XMC_Dokument> XMC_Dokument { get; set; }
        public virtual DbSet<XMCPozicion> XMCPozicions { get; set; }
        public virtual DbSet<XMCProjekt> XMCProjekts { get; set; }
        public virtual DbSet<XMCPune> XMCPunes { get; set; }
        public virtual DbSet<XMCStatistika> XMCStatistikas { get; set; }
        public virtual DbSet<XMCTask> XMCTasks { get; set; }
        public virtual DbSet<XMCTipologjia> XMCTipologjias { get; set; }
        public virtual DbSet<XMCUser> XMCUsers { get; set; }
    }
}
