//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMCPozicion
    {
        public XMCPozicion()
        {
            this.XMCUsers = new HashSet<XMCUser>();
        }
    
        public long XMCPozicion_Id { get; set; }
        public string Pozicion_Name { get; set; }
        public string Pozicion_Description { get; set; }
    
        public virtual ICollection<XMCUser> XMCUsers { get; set; }
    }
}
