//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMCTipologjia
    {
        public XMCTipologjia()
        {
            this.XMCTasks = new HashSet<XMCTask>();
        }
    
        public long XMCTipologjia_Id { get; set; }
        public string Tipologjia_Name { get; set; }
        public string Tipologjia_Description { get; set; }
    
        public virtual ICollection<XMCTask> XMCTasks { get; set; }
    }
}
