//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMCTipologjia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XMCTipologjia()
        {
            this.XMCTasks = new HashSet<XMCTask>();
        }
    
        public long XMCTipologjia_Id { get; set; }
        public string Tipologjia_Name { get; set; }
        public string Tipologjia_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XMCTask> XMCTasks { get; set; }
    }
}
