//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaXMCWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMCTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XMCTask()
        {
            this.XMC_Dokument = new HashSet<XMC_Dokument>();
        }
    
        public long XMCTask_Id { get; set; }
        public string Task_Name { get; set; }
        public string Task_Description { get; set; }
        public long Creator_Id { get; set; }
        public long Referencer_Id { get; set; }
        public long XMCPune_Id { get; set; }
        public long XMCProjekt_Id { get; set; }
        public long XMCTipologjia_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XMC_Dokument> XMC_Dokument { get; set; }
        public virtual XMCProjekt XMCProjekt { get; set; }
        public virtual XMCPune XMCPune { get; set; }
        public virtual XMCUser XMCUser { get; set; }
        public virtual XMCUser XMCUser1 { get; set; }
        public virtual XMCTipologjia XMCTipologjia { get; set; }
    }
}
